version: '3'
services:
    assembly:
        build:
            context: ./Assembly
            dockerfile: Dockerfile
        volumes:
            - 'CommonFiles:/usr/src/app/boxfuse-sample-java-war-hello/target'
    prod:
        build:
            context: ./Production
            dockerfile: Dockerfile
        ports:
             - '8080:8080'
        depends_on:
             - assembly
        volumes:
            - 'CommonFiles:/var/lib/tomcat8/webapps'
volumes:
    CommonFiles: